openapi: "3.0.0"
info:
  version: 1.0.0
  title: Couchbase Data API
paths:
  '/v1/callerIdentity':
    $ref: "./specs/resources/CallerIdentity.yaml"
  '/v1/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}':
    $ref: "./specs/resources/Documents.yaml"
  '/v1.alpha/enabled':
    $ref: "./specs/resources/AlphaEnabled.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/append':
    $ref: "./specs/resources/AppendToDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/prepend':
    $ref: "./specs/resources/PrependToDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/increment':
    $ref: "./specs/resources/IncrementDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/decrement':
    $ref: "./specs/resources/DecrementDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/lock':
    $ref: "./specs/resources/LockDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/unlock':
    $ref: "./specs/resources/UnlockDocument.yaml"
  '/v1.alpha/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}/touch':
    $ref: "./specs/resources/TouchDocument.yaml"
components:
  parameters:
    $ref: "./specs/parameters/_index.yaml"
  schemas:
    $ref: "./specs/schemas/_index.yaml"
  responses:
    $ref: "./specs/responses/_index.yaml"
  headers:
    $ref: "./specs/headers/_index.yaml"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic