openapi: "3.0.0"
info:
  version: 1.0.0
  title: Couchbase Data API
paths:
  '/v1/buckets/{bucketName}/scopes/{scopeName}/collections/{collectionName}/documents/{documentKey}':
    parameters:
      - $ref: '#/components/parameters/AuthorizationHeader'
      - $ref: '#/components/parameters/BucketName'
      - $ref: '#/components/parameters/ScopeName'
      - $ref: '#/components/parameters/CollectionName'
      - $ref: '#/components/parameters/DocumentKey'
    get:
      operationId: getDocument
      tags:
        - Single Document Operations
      parameters:
        - $ref: '#/components/parameters/AcceptEncodingHeader'
        - in: query
          name: project
          description: Specific fields to project from the document.
          required: false
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Successful fetch of the document
          headers:
            Content-Encoding:
              $ref: "#/components/headers/ContentEncoding"
            ETag:
              $ref: "#/components/headers/ETag"
            Expires:
              $ref: "#/components/headers/Expires"
            X-CB-Flags:
              $ref: "#/components/headers/DocumentFlags"
          content:
            '*':
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/BadRequest' 
        '403':
          $ref: '#/components/responses/Forbidden' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable' 
        '504':
          $ref: '#/components/responses/GatewayTimeout' 
    post:
      operationId: createDocument
      tags:
        - Single Document Operations
      parameters:
        - $ref: '#/components/parameters/ContentEncodingHeader'
        - $ref: '#/components/parameters/ExpiresHeader'
        - $ref: '#/components/parameters/DocumentFlagsHeader'
        - $ref: '#/components/parameters/DurabilityLevelHeader'
      requestBody:
        required: true
        content:
         '*':
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful creation of the document
          headers:
            ETag:
              $ref: "#/components/headers/ETag"
            X-CB-MutationToken:
              $ref: "#/components/headers/MutationToken"
        '400':
          $ref: '#/components/responses/BadRequest' 
        '403':
          $ref: '#/components/responses/Forbidden' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '409':
          $ref: '#/components/responses/Conflict' 
        '413':
          $ref: '#/components/responses/ContentTooLarge' 
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable' 
        '504':
          $ref: '#/components/responses/GatewayTimeout' 
    put:
      operationId: updateDocument
      tags:
        - Single Document Operations
      parameters:
        - $ref: '#/components/parameters/ContentEncodingHeader'
        - $ref: '#/components/parameters/IfMatchHeader'
        - $ref: '#/components/parameters/ExpiresHeader'
        - $ref: '#/components/parameters/DocumentFlagsHeader'
        - $ref: '#/components/parameters/DurabilityLevelHeader'
      requestBody:
        required: true
        content:
          '*':
            schema: {}
      responses:
        '200':
          description: Successful creation of the document
          headers:
            ETag:
              $ref: "#/components/headers/ETag"
            X-CB-MutationToken:
              $ref: "#/components/headers/MutationToken"
        '400':
          $ref: '#/components/responses/BadRequest' 
        '403':
          $ref: '#/components/responses/Forbidden' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '409':
          $ref: '#/components/responses/Conflict' 
        '413':
          $ref: '#/components/responses/ContentTooLarge' 
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable' 
        '504':
          $ref: '#/components/responses/GatewayTimeout' 
    delete:
      operationId: deleteDocument
      tags:
        - Single Document Operations
      parameters:
        - $ref: '#/components/parameters/IfMatchHeader'
        - $ref: '#/components/parameters/DurabilityLevelHeader'
      responses:
        '200':
          description: Successful deletion of the document
          headers:
            ETag:
              $ref: "#/components/headers/ETag"
            X-CB-MutationToken:
              $ref: "#/components/headers/MutationToken"
        '400':
          $ref: '#/components/responses/BadRequest' 
        '403':
          $ref: '#/components/responses/Forbidden' 
        '404':
          $ref: '#/components/responses/NotFound' 
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable' 
        '504':
          $ref: '#/components/responses/GatewayTimeout'
  '/v1.alpha/enabled':
    get:
      operationId: alphaEnabled
      responses:
        '200':
          description: The alpha API is enabled
        '404':
          description: The alpha API is not enabled
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  responses:
    BadRequest: # 400
      description: The request was malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden: # 403
      description: The user does not have permission to access the resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound: # 404
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict: # 409
      description: A conflict occurred while processing the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ContentTooLarge: # 413
      description: The document is too large to be stored
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError: # 500
      description: An internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable: # 503
      description: One of the underlying services was not available
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GatewayTimeout: # 504
      description: The request timed out
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    DocumentEncoding:
      title: DocumentEncoding
      description: DocumentEncoding specifies the compression used for the the document.
      type: string
      enum:
        - identity
        - snappy
      x-enum-varnames:
        - DocumentEncodingIdentity
        - DocumentEncodingSnappy
    DurabilityLevel:
      title: DurabilityLevel
      description: DurabilityLevel specifies the level of synchronous replication to use.
      type: string
      enum:
        - None
        - Majority
        - MajorityAndPersistOnMaster
        - PersitToMajority
      x-enum-varnames:
        - DurabilityLevelNone
        - DurabilityLevelMajority
        - DurabilityLevelMajorityAndPersistOnMaster
        - DurabilityLevelPersitToMajority
    ErrorCode:
      title: ErrorCode
      description: ErrorCode specifies the more specified error that occurred.
      type: string
      enum:
        - InvalidArgument
        - Unauthorized
        - NoReadAccess
        - NoWriteAccess
        - InvalidAuth
        - Internal
        - UnderlyingServiceUnavailable
        - RequestCanceled
        - DeadlineExceeded
        - BucketNotFound
        - ScopeNotFound
        - CollectionNotFound
        - DocumentNotFound
        - DocumentExists
        - CasMismatch
        - DocumentLocked
        - ValueTooLarge
        - DocumentNotJson
        - PathMismatch
      x-enum-varnames:
        - ErrorCodeInvalidArgument
        - ErrorCodeUnauthorized
        - ErrorCodeNoReadAccess
        - ErrorCodeNoWriteAccess
        - ErrorCodeInvalidAuth
        - ErrorCodeInternal
        - ErrorCodeUnderlyingServiceUnavailable
        - ErrorCodeRequestCanceled
        - ErrorCodeDeadlineExceeded
        - ErrorCodeBucketNotFound
        - ErrorCodeScopeNotFound
        - ErrorCodeCollectionNotFound
        - ErrorCodeDocumentNotFound
        - ErrorCodeDocumentExists
        - ErrorCodeCasMismatch
        - ErrorCodeDocumentLocked
        - ErrorCodeValueTooLarge
        - ErrorCodeDocumentNotJson
        - ErrorCodePathMismatch
    Error:
      title: Error
      description: Error represents an error response from the server.
      type: object
      properties:
        error:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          description: A human-readable description of the error.
        resource:
          type: string
          description: The resource that caused the error.
      required:
        - code
        - message
  parameters:
    AuthorizationHeader:
      in: header
      name: Authorization
      description: Header for authentication
      schema:
        type: string
      required: true
    AcceptEncodingHeader:
      in: header
      name: Accept-Encoding
      description: Specifies the compression used for the response in HTTP content-negotiation format.
      schema:
        type: string
    ContentEncodingHeader:
      in: header
      name: Content-Encoding
      description: The encoding of the document
      schema:
        $ref: '#/components/schemas/DocumentEncoding'
    IfMatchHeader:
      in: header
      name: If-Match
      description: The CAS of the document to check before updating.
      schema:
        type: string
    ExpiresHeader:
      in: header
      name: Expires
      description: The expiry time of the document.
      schema:
        type: string
    DocumentFlagsHeader:
      in: header
      name: X-CB-Flags
      description: The Flags of the document.
      schema:
        type: integer
        format: uint32
    DurabilityLevelHeader:
      in: header
      name: X-CB-DurabilityLevel
      description: The level of durability required for this write operation.
      schema:
        $ref: '#/components/schemas/DurabilityLevel'
    BucketName:
      in: path
      name: bucketName
      description: name of the bucket containing the document
      schema:
        type: string
      required: true
    ScopeName:
      in: path
      name: scopeName
      description: name of the scope containing the document
      schema:
        type: string
      required: true
    CollectionName:
      in: path
      name: collectionName
      description: name of the collection containing the document
      schema:
        type: string
      required: true
    DocumentKey:
      in: path
      name: documentKey
      description: name of the document
      schema:
        type: string
      required: true
  headers:
    ContentEncoding:
      description: The encoding of the document
      schema:
        $ref: '#/components/schemas/DocumentEncoding'
    ETag:
      description: The CAS of the document.
      schema:
        type: string
    Expires:
      description: The expiry time of the document represented as an ISO8601 string.
      schema:
        type: string
    DocumentFlags:
      description: The Flags of the document.
      schema:
        type: integer
        format: uint32
    MutationToken:
      schema:
        type: string
      description: A token representing the mutation of the document.