name: Run Data API Durability Impossible Tests
permissions:
  contents: read
  packages: read

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        server:
          - 8.0.0-3534
          - 7.6.5
          - 7.2.2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install cbdinocluster
        uses: ./.github/actions/install-cbdinocluster
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start couchbase cluster
        id: start-cluster
        uses: ./.github/actions/start-couchbase-cluster
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: arduino/setup-protoc@v3
        with:
          version: 31.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5
          go install github.com/matryer/moq@v0.5
      - name: Install Dependencies
        run: go get ./...
      - name: Generate Files
        run: |
          go generate ./...
      - name: Run Test
        env:
          SGTEST_CBCONNSTR: ${{ steps.start-cluster.outputs.node-ip }}
          SGTEST_DINOID: ${{ steps.start-cluster.outputs.dino-id }}
        run: go test ./gateway/test -run TestGatewayOps -v -testify.m TestDapiDurabilityImpossible

      - name: Collect couchbase logs
        timeout-minutes: 10
        if: failure()
        run: |
          mkdir -p ./dapi-durability-impossible-logs
          cbdinocluster -v collect-logs  ${{ steps.start-cluster.outputs.dino-id }} ./dapi-durability-impossible-logs
      - name: Upload couchbase logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cbcollect-logs-${{ matrix.server }}
          path: ./dapi-durability-impossible-logs/*
          retention-days: 5