name: Run Linter
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: arduino/setup-protoc@v1
        with:
          version: 3.17
      - run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - name: Generate Files
        run: |
          go generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51
          args: --timeout=3m
